version: '3'
services:
  nginx:
    build:
      context: .docker/nginx
    restart: unless-stopped
    tty: true
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_SSL_PORT:-443}:443"
    container_name: "${DOCKER_NGINX_NAME:-movie-catalog-api_nginx}"
    environment:
      SERVICE_NAME: movie-catalog-api_nginx
      TZ: "${APP_TIMEZONE:-America/Boa_Vista}"
    volumes:
      - '.:/var/www/html'
      - './.docker/nginx/nginx.local.conf:/etc/nginx/nginx.local.conf'
      - './.docker/nginx/conf.d/movie-catalog-api.local.conf:/etc/nginx/conf.d/movie-catalog-api.local.conf'
      - './.docker/nginx/logs:/var/log/nginx'
      - '/etc/letsencrypt/:/etc/letsencrypt/'
    networks:
      - movie-catalog-api-network
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    container_name: "${DOCKER_PHP_NAME:-movie-catalog-api_php}"
    environment:
      SERVICE_NAME: movie-catalog-api
      VIRTUAL_HOST: movie-catalog-api.local
      LOCALHOST_UID: 1001
      LOCALHOST_USERNAME: ${USER}
      PHP_IDE_CONFIG: 'serverName=xdebug-docker'
      TZ: "${APP_TIMEZONE:-America/Boa_Vista}"
      PHP_OPCACHE_MEMORY_CONSUMPTION: "${PHP_OPCACHE_MEMORY_CONSUMPTION:-192}"
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "${PHP_OPCACHE_VALIDATE_TIMESTAMPS:-1}"
      PHP_OPCACHE_MAX_ACCELERATED_FILES: "${PHP_OPCACHE_MAX_ACCELERATED_FILES:-10000}"
      PHP_OPCACHE_MAX_WASTED_PERCENTAGE: "${PHP_OPCACHE_MAX_WASTED_PERCENTAGE:-10}"
      PHP_OPCACHE_REVALIDATE_FREQ: "${PHP_OPCACHE_REVALIDATE_FREQ:-5}"
      PHP_OPCACHE_INTERNED_STRINGS_BUFFER: "${PHP_OPCACHE_INTERNED_STRINGS_BUFFER:-16}"
      PHP_OPCACHE_FAST_SHUTDOWN: "${PHP_OPCACHE_FAST_SHUTDOWN:-1}"
      PHP_OPCACHE_ENABLE_CLI: "${PHP_OPCACHE_ENABLE_CLI:-1}"
      PHP_OPCACHE_SAVE_COMMENTS: "${PHP_OPCACHE_SAVE_COMMENTS:-1}"
      PHP_OPCACHE_HUGE_CODE_PAGES: "${PHP_OPCACHE_HUGE_CODE_PAGES:-1}"
      PHP_OPCACHE_FILE_CACHE: "${PHP_OPCACHE_FILE_CACHE:-/tmp/opcache}"
      PHP_OPCACHE_PRELOAD: "${PHP_OPCACHE_PRELOAD:-/var/www/html/preload.php}"
    volumes:
      - '.:/var/www/html'
      - './.docker/php/php.ini:/usr/local/etc/php/php.ini'
      - './.docker/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini'
    networks:
      - movie-catalog-api-network
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
  node: # Novo serviço Node.js para o frontend
    build:
      context: .docker/node # O Dockerfile para o Node.js estará neste diretório
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    container_name: "${DOCKER_NODE_NAME:-movie-catalog-api_node}"
    environment:
      SERVICE_NAME: movie-catalog-api_node
      TZ: "${APP_TIMEZONE:-America/Boa_Vista}"
      LOCALHOST_UID: 1001
      LOCALHOST_USERNAME: ${USER}
    ports:
      - "${NODE_PORT:-5173}:5173"
    volumes:
      - '../movie-catalog-front:/app'
    networks:
      - movie-catalog-api-network
    # depends_on:
    #     - php-fpm
  redis:
    build:
      context: .docker/redis
      dockerfile: Dockerfile
    tty: true
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - './.docker/redis/data:/data'
    networks:
      - movie-catalog-api-network
    container_name: "${DOCKER_REDIS_NAME:-movie-catalog-api_redis}"
    environment:
      TZ: "${APP_TIMEZONE:-America/Boa_Vista}"
    command: redis-server --requirepass '${REDIS_PASSWORD}' --appendonly yes --replica-read-only no
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
  mysql:
    image: mysql:8.0
    container_name: "${DOCKER_MYSQL_NAME:-movie-catalog-api_mysql}"
    restart: unless-stopped
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      TZ: "${APP_TIMEZONE:-America/Boa_Vista}"
    volumes:
      - movie-catalog-api-mysql:/var/lib/mysql
    networks:
      - movie-catalog-api-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      retries: 3
      timeout: 5s
networks:
  movie-catalog-api-network:
    driver: bridge
volumes:
  movie-catalog-api-redis:
    driver: local
  movie-catalog-api-mysql:
    driver: local
